language: c

compiler:
  - clang

before_script:
  - sudo add-apt-repository --yes ppa:kalakris/cmake -qq
  - sudo apt-get update
  - sudo apt-get install pkg-config libudev-dev cmake -qq
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..

script: make && make test
