language: c

compiler:
  - clang

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install pkg-config libudev-dev -qq
  - cmake --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..

script: make && make test
